### ISSUE TITLE
Forward SSH key to Git4Windows

### ISSUE THREAD

**Issue by internetfreak** [rupor-github/win-gpg-agent#2]
Hello,

thanks for this project. I was first using wsl-ssh-pageant directly which you linked in your "Thanks" section, but you project seems to be more integrated and can be called directly without any hack to prevent empty console windows.
Using it as drop-in replacement works fine, however, git is still unable to pickup my key from neither CMD/PowerShell/Git Bash as it is not using the correct environment variable when it uses the ssh executable that comes with git.
I have managed to get it work by setting the following:
`GIT_SSH_COMMAND="C:\\Windows\\System32\\OpenSSH\\ssh"`
Can this variable get added to the program or is this the wrong place to look and I have something else to configure?

Thanks in advance

**Comment by rupor-github** [comment]
HI - there are too many ways to setup git on Windows those days. In order to answer properly I will have to know a bit more about what exactly you are using :) Standard "Git for Windows" set those days comes without it's own ssh executable and since it is compiled using mingw2 it probably expects/uses something like Cygwin sockets (much like assuan socket GnuPG is using) to communicate. Unfortunately as I wrote in README GnuPG own ssh support is presently broken under WIndows. So far I have no plans to specially support either Cygwin or Mingw environments in my code since IMHO with WSL 1/2/ interest should die out).

Having said all that, however using `git config --global` with `core.sshCommand` (rather then setting environment variables) should take care of all your needs 😄

**Comment by internetfreak** [comment]
Hi,

thanks for the reply. I installed Git4Windows with almost all defaults, especially regarding the use of other programs so git included only a few linux system tools in my PATH. If I execute `ssh -V` in git bash I get this:
`OpenSSH_8.4p1, OpenSSL 1.1.1i  8 Dec 2020`
For windows, I get this:
`OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5`
Searching for ssh.exe via `where.exe ssh` from PowerShell gives me the path of my windows openSSH executable
From what it looks like there are two ssh tools installed and git probably seems to use the included one.
I downloaded git from here: https://gitforwindows.org/

Anyway, I will test your suggestion with the git config instead of environment variables as all I want is to use git from PowerShell/CMD with my Nitrokey Smartcard as I would use ssh so as long as I can reproduce it in the future (in case of system changes or reinstalls) that's fine by me.

**Comment by rupor-github** [comment]
I will take a look at "GitF4Windows" and see what I can come up with. Personally I prefer to use the smallest set of tools possible (to avoid confusion and possible conflicts). For the OpenSSH which comes with Windows (OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5) - you probably would want to update it to https://github.com/PowerShell/openssh-portable/releases/tag/v8.1.0.0. IMHO the easiest way to do so is by using chocolatey `choco install openssh`, but you could simply copy binaries on top what has come with Windows.

**Comment by rupor-github** [comment]
@internetfreak - version 1.2.0 supports Cygwin socket "out of the box", you may consider updating 😄 Please, note that both native Windows OpenSSH and Cygwin/MSYS2 ssh (which comes with Git4Windows) are using the same `SSH_AUTH_SOCK` variable - but it needs to be set differently. So you cannot use both tools in the same session without carefully managing this variable.

**Comment by ran-dall** [comment]
@rupor-github I may have found a pretty clean workaround for Cygwin/MSYS* when using `openssh: native`, however, it requires you to install PuTTy, and add the following to your `~/.bashrc`...

```shell
# Use PuTTY Pageant for Cgywin & MSYS*
if [ $(uname -a | grep -c "CYGWIN") -eq 1 ] || [ $(uname -a | grep -c "Msys") -eq 1 ]; then
        eval $(/usr/bin/ssh-pageant -r -a "/tmp/.ssh-pageant-$USERNAME")
fi
```

I added the switch statement, just in case. You really don't need it though, cause I think only Cygwin/MSYS* use the `.bashrc` located in `winhome`. It's been a little while since I used Cygwin but I think that this is right also for Cygwin, and maybe other Msys-versions. Otherwise, it's pretty self-explanatory to update.

So far I've only used this with `git-bash` provided by Git for Windows, and it's been working for me 100%.

```shell
user@computer MINGW64 ~
$ eval $(/usr/bin/ssh-pageant -r -a "/tmp/.ssh-pageant-$USERNAME")
ssh-pageant pid 221

user@computer MINGW64 ~
$ ssh-add -l
xxxx SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx cardno:xxxxxxxxxxxx(xxx)   
```

**Comment by rupor-github** [comment]
@ran-dall My wish was to minimize usage of any additional "agents" because in each additional environment this comes with life-time management issues :)

So, there is always a possibility to approach it from the either end: either by specifying openssh cygwin and then adjusting SSH_AUTH_SOCK for native environment(s) manually (note that "\\.\pipe\openssh-ssh-agent" is always there for you) or even (nuclear option) by setting `setenv: false` and preparing variables in each environment "by hand" to avoid conflicts. 

In your case however simple line in .bashrc should work perfectly:

    export SSH_AUTH_SOCK=$(cygpath ${WSL_AGENT_HOME})/S.gpg-agent.ssh.cyg

**Comment by ran-dall** [comment]
@rupor-github Thanks for sharing your viewpoint.

> My hope was to minimize usage of any additional "agents" because in each additional environment this comes with life-time management issues :)

This is a good point; however, (at least on mine) `pageant` support is already enabled. The only difference is that we're actually using it. So I wouldn't consider we're really adding another agent, as opposed to just installing another piece of software (which has been part of the Windows SSH toolchain for a long while) that communicates with the GPG agent. Furthermore, considering you shouldn't share GPG keychains between environments (which is recommended by WSL and Cygwin/MINGW* users because of potential permission issues), I think it makes sense. Nevertheless, installing more software is never an elegant solution.

> So, there is always a possibility to approach it from the either end: either by specifying openssh cygwin and then adjusting SSH_AUTH_SOCK for native environment(s) manually (note that "\.\pipe\openssh-ssh-agent" is always there for you) or even (nuclear option) by setting setenv: false and preparing variables in each environment "by hand" to avoid conflicts.

I notice that too, so I agree, and NTM, this hardly even seems practical.

> In your case however simple line in .bashrc should work perfectly:
> ``` shell
> export SSH_AUTH_SOCK=$(cygpath ${WSL_AGENT_HOME})/S.gpg-agent.ssh.cyg
> ```

I actually tried this before, but I didn't go with it because (in my tests) Native OpenSSH performance is superior to MINGW64's OpenSSH (which is the default that comes with Git for Windows), and compatiablity-wise, Native OpenSSH is more compatible with Windows-based tooling. For example, I use [Token2Shell](https://token2shell.com/) (and a couple of other things) for `SSH2`, and they all fail when using MINGW64 OpenSSH. Also, [Tower for Windows](https://www.git-tower.com/windows) seems to prefer the Native OpenSSH setup, as the MINGW64 OpenSSH setup tends to time out easily on Tower. However, I think you provide an alternative good approach if you don't want to install PuTTY, don't mind the (slight+) performance plenty, and/or your tooling is mostly `cygwin`/ `MINGW*` (or maybe `scoop`) based.

With all that said, I said you updated the `README.md` with your suggestion. Maybe it would be wise also to include my workaround for Native OpenSSH users in a similar boat?

**Comment by rupor-github** [comment]
@ran-dall It is quite possible that I am missing something here. For me native is WIn32-OpenSSH natively compiled for Windows environment which comes with WIndows 10 and could be [updated](https://github.com/PowerShell/Win32-OpenSSH). Everything else is compiled either with cygwin or mingw emulation environment and that includes git-bash from Git4Windows.

I do not see how you are using what you call "native" in you solution. What you are suggesting instead is to use mingw's [ssh-pageant](https://github.com/cuviper/ssh-pageant) to provide cygwin/mingw "unix" socket in mingw environment for mingw ssh implementation (and every tool which is using this ssh implementation).

Internally ssh-pageant reaches out from mingw environment to the outside pageant compatible shared memory buffer (implemented by gnupg) and translates this into socket `/tmp/.ssh-pageant-$USERNAME` - hence it does EXACTLY the same thing as win-gpg-agent and `S.gpg-agent.ssh.cyg` already provided for this purpose. Or rather the other way around - win-agent-gui does exactly the same thing ssh-pageant does (singe ssh-pageant historically was implemented before win-gpg-agent). As the matter of fact win-gpg-agent documentation mentioned that win-gpg-agent has to use pageant protocol in multiple places, because gpg-agent.ssh Assuan socket does not work. So unless I am missing something you suggest using additional program for what is already there and being done by win-gpg-agent itself. I fail to see why this is needed at all and why I should document this as `a pretty clean workaround` for a problem which does not exists.

Performance wise it is quite possible that GoLang implementation of translation from pageant compatible shared memory from gnupg to standard TCP socket is slower than is afforded by c implementation, however so far I see absolutely nothing to substantiate this claim.

Similar could be said about compatibility. It is true that some tools may expect mingw completed OpenSSH while other may prefer native Win32-OpenSSH. Today both are built from the same code base and both have very similar version -  `OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021` for git-bash and `OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3 ` for native Win32-OpenSSH. As the matter of fact Windows "native" is even more recent. So it comes down for ease of use and resulting security implications - exactly why I created win-gpg-agent in a first place.

**Comment by ran-dall** [comment]
@rupor-github NP.

> For me native is WIn32-OpenSSH natively compiled for Windows environment which comes with WIndows 10 and could be updated. Everything else is compiled either with cygwin or mingw emulation environment and that includes git-bash from Git4Windows.

This is correct. I'd be talking about Win32-OpenSSH.

> Internally ssh-pageant reaches out from mingw environment to the outside pageant compatible shared memory buffer (implemented by gnupg rather than Putty's pageant) and translates this into socket /tmp/.ssh-pageant-$USERNAME - hence it does EXACTLY the same thing as win-gpg-agent and S.gpg-agent.ssh.cyg already provided for this purpose. Or rather the other way around - win-agent-gui does exactly the same thing ssh-pageant does (singe ssh-pageant historically was implemented before win-gpg-agent). As the matter of fact win-gpg-agent documentation mentioned that win-gpg-agent has to use pageant protocol in multiple places, because gpg-agent.ssh Assuan socket does not work. So unless I am missing something you suggest using additional program for what is already there and being done by win-gpg-agent itself. 

> Performance wise it is quite possible that GoLang implementation of translation from pageant compatible shared memory from gnupg to standard TCP socket is slower than is afforded by c implementation, however so far I see absolutely nothing to substantiate this claim.

When I activate `openssh: cygwin` to use `S.gpg-agent.ssh.cyg`, I can't use it for access from Powershell (cause the agent only creates the pipe or the UNIX socket, but never both). This is, of course, unless I set up the environment to use `S.gpg-agent.ssh.cyg, However, doing so adds about an additional second to the PowerShell start-up time, which is what I'm mainly using to benchmark, as these are new systems and don't have anything else installed by Git for Windows, Gpg4Win, PuTTY, `scoop` and the agent. I also use some of ssh's basic benchmark tools with `ssh git@github`, which also confirm that `openssh: cygwin` is slower than `openssh: native` on the 6 different systems have with this setup. You're more than welcome to benchmark it yourself, to see for yourself.

Also, FTR, I did read that `win-gpg-agent` uses ssh pageant protocol, but I wasn't able to make it work by itself without PuTTY.

> I fail to see why this is needed at all and why I should document this as a pretty clean workaround for a problem which does not exist.

I appreciate the explanation, although I don't appreciate the abrasiveness, as we're all trying to help further your already impressive efforts. I apologize if I offended you somehow, but adding saltiness and sassiness to this conversation I hardly think is appropriate.

> Similar could be said about compatibility. It is true that some tools may expect mingw completed OpenSSH while other may prefer native Win32-OpenSSH. Multiple tools like Putty and WinSCP and FAR manager plugins and similar tools which do access pageant memory buffer work transparently today as do mingw/cygwin based tools without a need for additional translations or agents lifetime management because all OpenSSH implementations are built from the same code base and both have very similar versions - OpenSSH_8.5p1, OpenSSL 1.1.1k 25 Mar 2021 for git-bash and OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3 for native Win32-OpenSSH. As the matter of fact Windows "native" is even more recent. So it comes down for ease of use and resulting security implications - exactly why I created win-gpg-agent in a first place.

We agree. It really comes down to ease of use and the resulting security implications (and performance a little, IME).

---

With all that said, please allow me to clarify what I'm suggesting...

First off, `openssh: cygwin` isn't really an option for me because most of our Windows tooling is PowerShell / WSL based. Aside from the slight performance difference experienced, a lot of the tooling (such as [wslgit](https://github.com/andy-5/wslgit)) don't like to use the `openssh: cygwin` setup at all or without a slight-moderate performance penalty. So, therefore, `openssh: native` is the only real option, IMO.

That said, `openssh: native` only creates the pipe, and no `S.gpg-agent.ssh.cyg` socket. Now because of the lack of a real `socat` implementation on `cygwin` and `MINGW*`, we can't really use any real sort of pipes. So, therefore, I need the socket...but (as we already know) the socket isn't available in `openssh: native`. 

So what I'm suggesting is recreating the missing `S.gpg-agent.ssh.cyg` socket in `/tmp/.ssh-pageant-$USERNAME` with the help of PuTTY and hooking it up to authenticate with already running the GPG agent that has the keys loaded from (my) Yubikey. 

I suppose if we made an additional `openssh:` option to have both available (so that I have both the pipe and `S.gpg-agent.ssh.cyg` socket available), then I could use your fix for only the `cygwin` / `MINGW*` systems and not have to really depend on anything else at all. I think that this would probably be optimal for this scenario cause then you really wouldn't even need to install PuTTY or anything else.

**Comment by rupor-github** [comment]
I am sorry, but I am afraid you are making wrong assumptions:

**Regardless of the value of `openssh` option (native|cygwin) both cygwin socket and named pipe are ALWAYS created**. I tried to emphasize this in the readme, probably not enough, but it is very easy to try. Value of this configuration only influences what will be automatically registered as SSH_AUTH_SOCK in the environments - not provided services themselves. If named pipe is not available when you are using `openssh: cygwin` - it's a bug. You do not need to activate `openssh: cygwin` to use `S.gpg-agent.ssh.cyg`. If cygwin socket is not available when you are using `openssh: native` - it's a bug too, however this is exactly how I am using it. Here is what I have as agent-gui.conf:

```
gpg:
  install_path: "${USERPROFILE}\\scoop\\apps\\gnupg\\current"
  homedir: "${USERPROFILE}\\scoop\\apps\\gnupg\\current\\home"
gui:
  debug: true
  setenv: true
  # Uncomment line below to enable SSH_AUTH_SOCK to point to cygwin socket
  #openssh: cygwin
  extra_port: 19321
  gclpr:
    public_keys:
       ...
```
And here is `git-bash` window from Git4Windows:
![Clipboard01](https://user-images.githubusercontent.com/5368784/120250206-4c196300-c24b-11eb-9d93-03b688ffc8e8.jpg)

Here is powershell window on the same box using Win32-OpenSSH:
![Clipboard02](https://user-images.githubusercontent.com/5368784/120250218-54719e00-c24b-11eb-9c42-b0adc8d1684d.jpg)

The reason why powershell has delay is because you are initializing the whole mingw environment every time - not because mingw implementation of SSH is slower 😄 Be it as it may - if you want to use native version with Git4Windows - you have to configure git (.gitconfig core.sshCommand as described above, not SSH environment variables as this would not help).

At the moment win-gpg-agent supports most if not all possible combinations for all available tools (or so I hope) - **you just have to carefully manage your environment settings** as you cannot set SSH_AUTH_SOCK on Windows end to be used in the same environment by all the tools at the same time for reasons which we do not control. 

If you find unsupported use case - please, let me know. Getting back to what you were suggesting initially - I really hope I illustrated that this is one of initially unsupported cases which is supported since v1.2.0 and is such you suggested use of ssh-pageant is unnecessary.

**Comment by ran-dall** [comment]
@rupor-github Thanks for your insight. 

> Regardless of the value of openssh option (native|cygwin), both cygwin socket and named pipe are ALWAYS created. I tried to emphasize this in the readme, probably not enough. If you set setenv: false as I explained in my very first answer - no environment variables will be set at all, but both named pipe and cygwin sock will be created anyways and you would have to do everything by hand. All of that is in documentation (may be not in the best possible way) but it is very easy to try. Value of this configuration only influences what will be automatically registered as SSH_AUTH_SOCK in the environments - not provided services themselves. If named pipe is not available when you are using openssh: cygwin - it's a bug. You do not need to activate openssh: native to use S.gpg-agent.ssh.cyg. If cygwin socket is not available when you are using openssh: native - it's a bug too, however this is exactly how I am using it. ...

I see what you're saying now, and I'm also using the `openssh: native` setup in all the machines I have this up in. However, I will say that I do think there's a bug with `openssh: cygwin` because it seems to make the pipe fail, in my experience. Hence, I used `openssh: native` as I'm more PowerShell based.

However, that said, for some reason, I still seem to have a hard time working some Windows-based tooling directly with the `S.gpg-agent.ssh.cyg` socket (and sometimes even the named pipe); but I think this comes back to what we discussed before about certain Windows tools preferring to access the pageant memory buffer's cached keys. It does bring up an interesting point though because even though we now seem to have both `S.gpg-agent.ssh.cyg` and `pagent`, and both seem suitable for use; however, it would seem that `S.gpg-agent.ssh.cyg` is not a complete 100% compatible replacement of `pagent`, as `pagent` seems to be more universally compatible including use with `cygwin` and `MINGW*`.

I also do still think though that your characterization of 'adding another agent' is incorrect though, because I'm not suggesting adding PuTTY's `pagent`, but rather using GPG's pagent support as `pagent`.

> The reason why powershell has delay is because you are initializing the whole mingw environment every time - not because mingw implementation of SSH is slower 😄 Be it as it may - if you want to use native version with Git4Windows - you have to configure git (.gitconfig core.sshCommand as described above, not SSH environment variables as this would not help).

Agreed. Although I will say that I did notice `MINGW64` does lag a second or two behind PowerShell when trying to establish the same connection. I'm assuming it's because of certain optimizations that have been baked into PowerShell, which is a far more recent (and modern) product than `MINGW64`. 

> At the moment win-gpg-agent supports most if not all possible combinations for all available tools (or so I hope) - you have to carefully manage your environment settings as you cannot set SSH_AUTH_SOCK on Windows end to be used in the same environment by all the tools at the same time for reasons which we do not control.

Agreed. Especially if you're not gonna depend on the environment being set by the agent.

> If you find unsupported use case - please, let me know. Getting back to what you were suggesting initially - I really hope I illustrated that this is one of initially unsupported cases which is supported since v1.2.0 and is such you suggested use of ssh-pageant is unnecessary.

As I mentioned above maybe if you're dependant on some of the Windows-based tooling (such as PuTTY) that prefers to use `pageant`.

**Comment by rupor-github** [comment]
@ran-dall if you have some use cases/scenarios which I could reproduce to allow me to see that "however, it would seem that S.gpg-agent.ssh.cyg is not a complete 100% compatible replacement of pagent, as pagent seems to be more universally compatible including use with cygwin, MINGW*, PuTTY, WinSCP, and other tools; where S.gpg-agent.ssh.cyg only seems to address the use of cygwin and MINGW*." - I will investigate.

**Comment by ran-dall** [comment]
@rupor-github I'm glad we're doing these rounds and clarifying things up. You know there are not that many people that really talk about / work on this stuff anymore. Regardless, I'm eternally grateful for your work, and I'm up for a fourth-round if needed. 😁

That said, I'd like to make a clarification. PuTTY is, in fact, not required to use `pageant`. In fact, I've completely removed PuTTY from 2 of my machines and I can still use `ssh-pageant` and `pageant` from within `MINGW64`

```shell
ssh-pageant pid 412

user@computer MINGW64 ~
$ ssh-add -l
xxxx SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx cardno:xxxxxxxxxxxx (xxx)
```

> I would like to point out, that pageant has nothing to do with S.gpg-agent.ssh.cyg, ssh-pageant does.

Correct. `pageant` is a protocol for Windows, usually implemented by PuTTY's `pageant.exe` or `gpg-agent --enable-putty-suport ...`. `S.gpg-agent.ssh.cyg` is the specific Cgywin socket that's created by `win-gpg-agent`. "`ssh-pageant` is a tiny tool for Windows that allows you to use SSH keys from PuTTY's Pageant in Cygwin and MSYS shell environments."

> Pageant and gnupg gpg agent are both implementing the same shared memory protocol which is used (among others) by putty, WinSCP and cygwin's ssh-pageant.

Correct! But they don't appear to be able to run at the same time. If `gpg-agent --enable-putty-suport ...` is enabled, Putty's Pageant will report that "Pageant is already running," which is really the `gpg-agent` with `--enable-putty-suport`. 

![image](https://user-images.githubusercontent.com/17261190/120368754-50836180-c2c7-11eb-9fab-7847c36f1c22.png)

> Ssh-pageant, wsl-ssh-pageant, win-gpg-agent (among others) are interfacing with underlying certificate storage via this pageant shared memory protocol providing interfaces for various other programs which do not know how to use pageant shared memory protocol.

Agreed.

> So win-gpg-agent provides AF_UNIX socket and Cygwin socket, ssh-pageant provides Cygwin socket, gpg-agent provides Assuan socket all sitting on top of pageant protocol.

Correct, however, `ssh-pageant` works specifically with whichever `pageant` you're running on the Windows side.

> You probably would need to be much more concrete when defining what "it would seem that S.gpg-agent.ssh.cyg is not a complete 100% compatible replacement of pagent, as pagent seems to be more universally compatible including use with cygwin, MINGW*, PuTTY, WinSCP, and other tools; where S.gpg-agent.ssh.cyg only seems to address the use of cygwin and MINGW* means, because of the above.

So it seems there is very little use-case for `S.gpg-agent.ssh.cyg`. I would say only for the few `MINGW*` builds that don't have `ssh-pageant` packed into it as `MINGW64` does (I read somewhere that MSYS2 doesn't have `ssh-pageant`, for example. 

It would be my recommendation, [like that of Yubico](https://developers.yubico.com/PGP/SSH_authentication/Windows.html), and [Git for Windows](https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant) to prefer to use `ssh-pageant` where available, and only use `S.gpg-agent.ssh.cyg` in cases where it isn't. This seems to allow for the most flexibility between programs and environments.

> If you could provide some use cases/scenarios which I could reproduce to allow me to see that - I will investigate each of those cases, otherwise - I think we are going in circles for the third time in a row 😄

PuTTY, WinSCP, Far, CyberDuck, Token2Shell, Tower for Windows, etc...

Mostly Windows tools it seems.

Hope that clears everything up for you. 🙃
