### ISSUE TITLE
Feature Request: Xshell (Xagent) support

### ISSUE THREAD

**Issue by Editst** [rupor-github/win-gpg-agent#21]
Hi, could you pleace consider add Xshell (Xagent) support, perhaps you can refer to [these codes](https://github.com/buptczq/WinCryptSSHAgent/blob/master/utils/xagent.go).

Thanks.

**Comment by rupor-github** [comment]
Looking at WinCryptSSHAgent code I honestly not sure... How popular XShell/XAgent is? Is this protocol documented somewhere? To me it looks like proprietary protocol from inside of commercial closed source application. So once put in - I will have to follow every time closed source implementation changes. And since they charge $99 a license - maybe they could start supporting either Windows or Cygwin instead?

**Comment by Editst** [comment]
In fact Xshell is widely used, and it offers [free licensing](https://www.netsarang.com/en/free-for-home-school/) for any personal non-commercial use. Xagent and Xshell are independent of each other, you can just foucs on Xagent which doesn't change often.  The only documentation I could find for Xagent is [this](https://netsarang.atlassian.net/wiki/spaces/ENSUP/pages/419957237/Using+Xagent).

**Comment by rupor-github** [comment]
https://github.com/rupor-github/win-gpg-agent/releases/tag/v1.5.0https://github.com/rupor-github/win-gpg-agent/releases/tag/v1.5.0
